name: Build as library

on:
  push:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgmp-dev

      - name: Configure
        run: cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}/ci/build

      - name: Build and run
        working-directory: ${{ github.workspace }}/build
        run: |
          make -j8
          ./Build
