name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        c_compiler: [gcc, clang]
        target: [Library_Integration, Readme_Examples]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B ${{ github.workspace }}/ci/integration/cmake-build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}/ci/integration

      - name: Build and run
        working-directory: ${{ github.workspace }}/ci/integration/cmake-build
        run: |
          cmake --build . --target ${{ matrix.target }} -j8
          ./${{ matrix.target }}
