name: Sanitize

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'sanitize/**'
      - '.github/workflows/sanitize_multiple_platforms.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'sanitize/**'
      - '.github/workflows/sanitize_multiple_platforms.yml'

jobs:
  Run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        c_compiler: [gcc, clang]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B ${{ github.workspace }}/sanitize/unsigned/cmake-build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}/sanitize/unsigned

      - name: Build
        run: cmake --build ${{ github.workspace }}/sanitize/unsigned/cmake-build --target AesiSanitize -j8

      - name: Run
        working-directory: ${{ github.workspace }}/sanitize/unsigned/cmake-build
        run: ./AesiSanitize
