name: Upload a release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release archive
        run: |
          zip Aesi_${{ inputs.version }}.zip Aesi.h Aeu.h README.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archive
          path: Aesi_${{ inputs.version }}.zip

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --title "Release ${{ inputs.version }}" \
            "${{ github.ref_name }}" \
            Aesi_universal_${{ inputs.version }}.zip